### PR TITLE
PMM-6007 : set login banner

### PR DESCRIPTION
**Pull request by AlyHKafoury**

### CODE REVIEW

**Comment by EvgeniyPatlan** [comment]
it would be great to have FB to prove that this works correctly

**Comment by AlyHKafoury** [comment]
@EvgeniyPatlan how init a FB for this pr ?

**Comment by EvgeniyPatlan** [comment]
> @EvgeniyPatlan how init a FB for this pr ?

At least you need to build Virtualbox and verify that you changes works correctly. Please verify if it is possible yo do this via standard FB. if no - please just build it locally or in jenkins to prove that your code works well

**Comment by AlyHKafoury** [comment]
@EvgeniyPatlan I've built it local on packer ovf and it works correctly

**Comment by EvgeniyPatlan** [comment]
> @EvgeniyPatlan I've built it local on packer ovf and it works correctly

where I can see for example screenshot?

**Comment by AlyHKafoury** [comment]
Screen Shot 2020-11-16 at 10 20 32 PM
@EvgeniyPatlan

**Review by EvgeniyPatlan — APPROVED** [review]

**Pull request merged**
